on:
  push:
    branches:
      - master

jobs:
  kiwi-test-manifest-example:
    runs-on: ubuntu-latest
    name: kiwi (manifest)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: Test
        uses:  operator-framework/community-operators@v1
        with:
          test-type: 'kiwi'
          stream: 'upstream-community-operators'
          name: 'aqua'
          version: '5.3.0'
          operator-version-path: my/op/manifest
          package-path: my/op/aqua-operator.package.yaml
          ci-path: my/op/ci.yaml

  kiwi-test-bundle-example:
    runs-on: ubuntu-latest
    name: kiwi (bundle)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: Test
        uses:  operator-framework/community-operators@v1
        with:
          test-type: 'kiwi'
          stream: 'upstream-community-operators'
          name: 'cockroachdb'
          version: '5.0.4'
          operator-version-path: my/op/bundle
